defmodule StarkInfra.PixPullSubscription.Log do
  alias __MODULE__, as: Log
  alias StarkInfra.Utils.Rest
  alias StarkInfra.Utils.API
  alias StarkInfra.Utils.Check
  alias StarkInfra.PixPullSubscription
  alias StarkInfra.User.Project
  alias StarkInfra.User.Organization
  alias StarkInfra.Error

  @moduledoc """
  Groups PixPullSubscription.Log related functions
  """

  @doc """
  Every time a PixPullSubscription entity is modified, a corresponding PixPullSubscription.Log
  is generated for the entity. This log is never generated by the user.

  ## Attributes (return-only):
    - `:id` [string]: unique id returned when the log is created. ex: "5656565656565656"
    - `:subscription` [PixPullSubscription]: PixPullSubscription entity to which the log refers to.
    - `:type` [string]: type of the PixPullSubscription event which triggered the log creation. ex: "created", "registered", "updated", "failed", "canceling", "canceled"
    - `:errors` [list of strings]: list of errors linked to this PixPullSubscription event
    - `:created` [DateTime]: creation datetime for the log. ex: ~U[2020-3-10 10:30:0:0]
  """
  @enforce_keys [
    :id,
    :subscription,
    :type,
    :errors,
    :created
  ]
  defstruct [
    :id,
    :subscription,
    :type,
    :errors,
    :created
  ]

  @type t() :: %__MODULE__{}

  @doc """
  Receive a single PixPullSubscription.Log struct previously created by the Stark Infra API by its id

  ## Parameters (required):
    - `:id` [string]: struct unique id. ex: "5656565656565656"

  ## Options:
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - PixPullSubscription.Log struct with updated attributes
  """
  @spec get(
    id: binary,
    user: Project.t() | Organization.t() | nil
  ) ::
    {:ok, Log.t()} |
    {:error, [Error.t()]}
  def get(id, options \\ []) do
    Rest.get_id(resource(), id, options)
  end

  @doc """
  Same as get(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec get!(
    id: binary,
    user: Project.t() | Organization.t() | nil
  ) :: Log.t()
  def get!(id, options \\ []) do
    Rest.get_id!(resource(), id, options)
  end

  @doc """
  Receive a stream of PixPullSubscription.Log structs previously created in the Stark Infra API

  ## Options:
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:limit` [integer, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
    - `:after` [Date or string, default nil]: date filter for structs created after specified date. ex: ~D[2020-03-10]
    - `:before` [Date or string, default nil]: date filter for structs created before a specified date. ex: ~D[2020-03-10]
    - `:types` [list of strings, default nil]: filter retrieved structs by types. Options: "created", "registered", "updated", "failed", "canceling", "canceled"
    - `:subscription_ids` [list of strings, default nil]: list of PixPullSubscription ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - stream of PixPullSubscription.Log structs with updated attributes
  """
  @spec query(
    ids: [binary],
    limit: integer,
    after: Date.t() | binary,
    before: Date.t() | binary,
    types: [binary],
    subscription_ids: [binary],
    user: Project.t() | Organization.t() | nil
  ) ::
    {:ok, [Log.t()]} |
    {:error, [Error.t()]}
  def query(options \\ []) do
    Rest.get_list(resource(), options)
  end

  @doc """
  Same as query(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec query!(
    ids: [binary],
    limit: integer,
    after: Date.t() | binary,
    before: Date.t() | binary,
    types: [binary],
    subscription_ids: [binary],
    user: Project.t() | Organization.t() | nil
  ) :: [Log.t()]
  def query!(options \\ []) do
    Rest.get_list!(resource(), options)
  end

  @doc """
  Receive a list of up to 100 PixPullSubscription.Log structs previously created in the Stark Infra API and the cursor to the next page.
  Use this function instead of query if you want to manually page your requests.

  ## Options:
    - `:cursor` [string, default nil]: cursor returned on the previous page function call
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:limit` [integer, default 100]: maximum number of structs to be retrieved. Max = 100. ex: 35
    - `:after` [Date or string, default nil]: date filter for structs created after a specified date. ex: ~D[2020-03-10]
    - `:before` [Date or string, default nil]: date filter for structs created before a specified date. ex: ~D[2020-03-10]
    - `:types` [list of strings, default nil]: filter retrieved structs by types. Options: "created", "registered", "updated", "failed", "canceling", "canceled"
    - `:subscription_ids` [list of strings, default nil]: list of PixPullSubscription ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - list of PixPullSubscription.Log structs with updated attributes
    - cursor to retrieve the next page of PixPullSubscription.Log structs
  """
  @spec page(
    cursor: binary,
    ids: [binary],
    limit: integer,
    after: Date.t() | binary,
    before: Date.t() | binary,
    types: [binary],
    subscription_ids: [binary],
    user: Project.t() | Organization.t() | nil
  ) ::
    {:ok, {binary, [Log.t()]}} |
    {:error, [Error.t()]}
  def page(options \\ []) do
    Rest.get_page(resource(), options)
  end

  @doc """
  Same as page(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec page!(
    cursor: binary,
    ids: [binary],
    limit: integer,
    after: Date.t() | binary,
    before: Date.t() | binary,
    types: [binary],
    subscription_ids: [binary],
    user: Project.t() | Organization.t() | nil
  ) ::
    {binary, [Log.t()]}
  def page!(options \\ []) do
    Rest.get_page!(resource(), options)
  end

  @doc false
  def resource() do
    {
      "PixPullSubscriptionLog",
      &resource_maker/1
    }
  end

  @doc false
  def resource_maker(json) do
    %Log{
      id: json[:id],
      subscription: json[:subscription] |> API.from_api_json(&PixPullSubscription.resource_maker/1),
      type: json[:type],
      errors: json[:errors],
      created: json[:created] |> Check.datetime()
    }
  end
end
