defmodule StarkInfra.Ledger.Log do
  alias __MODULE__, as: Log
  alias StarkInfra.Utils.Rest
  alias StarkInfra.Utils.API
  alias StarkInfra.Utils.Check
  alias StarkInfra.Ledger
  alias StarkInfra.User.Project
  alias StarkInfra.User.Organization
  alias StarkInfra.Error

  @moduledoc """
  Groups Ledger.Log related functions
  """

  @doc """
  Every time a Ledger entity is updated, a corresponding Ledger.Log
  is generated for the entity. This log is never generated by the user, but
  it can be retrieved to check additional information on the Ledger.

  ## Attributes:
    - `:id` [string]: unique id returned when the log is created. ex: "5656565656565656"
    - `:created` [DateTime]: creation datetime for the log. ex: ~U[2020-3-10 10:30:0:0]
    - `:type` [string]: type of the Ledger event which triggered the log creation. ex: "created", "updated"
    - `:ledger` [Ledger]: Ledger entity to which the log refers to.
  """
  @enforce_keys [
    :id,
    :created,
    :type,
    :ledger
  ]
  defstruct [
    :id,
    :created,
    :type,
    :ledger
  ]

  @type t() :: %__MODULE__{}

  @doc """
  Receive a single Ledger.Log struct previously created by the Stark Infra API by its id

  ## Parameters (required):
    - `:id` [string]: struct unique id. ex: "5656565656565656"

  ## Options:
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - Ledger.Log struct with updated attributes
  """
  @spec get(
    binary,
    user: Project.t() | Organization.t() | nil
  ) ::
    {:ok, Log.t()} |
    {:error, [Error.t()]}
  def get(id, options \\ []) do
    Rest.get_id(resource(), id, options)
  end

  @doc """
  Same as get(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec get!(
    binary,
    user: Project.t() | Organization.t() | nil
  ) :: any
  def get!(id, options \\ []) do
    Rest.get_id!(resource(), id, options)
  end

  @doc """
  Receive a stream of Ledger.Log structs previously created in the Stark Infra API

  ## Options:
    - `:ids` [list of strings, default nil]: Log ids to filter Ledger Logs. ex: ["5656565656565656"]
    - `:limit` [integer, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
    - `:after` [Date or string, default nil]: date filter for structs created after specified date. ex: ~D[2020-03-10]
    - `:before` [Date or string, default nil]: date filter for structs created before a specified date. ex: ~D[2020-03-10]
    - `:ledger_id` [string, default nil]: filter logs by Ledger id. ex: "5656565656565656"
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - stream of Ledger.Log structs with updated attributes
  """
  @spec query(
    ids: [binary] | nil,
    limit: integer | nil,
    after: Date.t() | binary | nil,
    before: Date.t() | binary | nil,
    ledger_id: binary | nil,
    user: Project.t() | Organization.t() | nil
  ) ::
    ({:cont, {:ok, [Log.t() | map]}} |
    {:error, [Error.t()]} |
    {:halt, any} |
    {:suspend, any},
    any ->  any)
  def query(options \\ []) do
    Rest.get_list(resource(), options)
  end

  @doc """
  Same as query(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec query!(
    ids: [binary] | nil,
    limit: integer | nil,
    after: Date.t() | binary | nil,
    before: Date.t() | binary | nil,
    ledger_id: binary | nil,
    user: Project.t() | Organization.t() | nil
  ) :: any
  def query!(options \\ []) do
    Rest.get_list!(resource(), options)
  end

  @doc """
  Receive a list of up to 100 Ledger.Log structs previously created in the Stark Infra API and the cursor to the next page.
  Use this function instead of query if you want to manually page your requests.

  ## Options:
    - `:cursor` [string, default nil]: cursor returned on the previous page function call
    - `:ids` [list of strings, default nil]: Log ids to filter Ledger Logs. ex: ["5656565656565656"]
    - `:limit` [integer, default 100]: maximum number of structs to be retrieved. Max = 100. ex: 35
    - `:after` [Date or string, default nil]: date filter for structs created after specified date. ex: ~D[2020-03-10]
    - `:before` [Date or string, default nil]: date filter for structs created before a specified date. ex: ~D[2020-03-10]
    - `:ledger_id` [string, default nil]: filter logs by Ledger id. ex: "5656565656565656"
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - list of Ledger.Log structs with updated attributes
    - cursor to retrieve the next page of Ledger.Log structs
  """
  @spec page(
    cursor: binary | nil,
    ids: [binary] | nil,
    limit: integer | nil,
    after: Date.t() | binary | nil,
    before: Date.t() | binary | nil,
    ledger_id: binary | nil,
    user: Project.t() | Organization.t() | nil
  ) ::
    {:ok, {binary, [Log.t()]}} |
    {:error, [Error.t()]}
  def page(options \\ []) do
    Rest.get_page(resource(), options)
  end

  @doc """
  Same as page(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec page!(
    cursor: binary | nil,
    ids: [binary] | nil,
    limit: integer | nil,
    after: Date.t() | binary | nil,
    before: Date.t() | binary | nil,
    ledger_id: binary | nil,
    user: Project.t() | Organization.t() | nil
  ) :: any
  def page!(options \\ []) do
    Rest.get_page!(resource(), options)
  end

  @doc false
  def resource() do
    {
      "LedgerLog",
      &resource_maker/1
    }
  end

  @doc false
  def resource_maker(json) do
    %Log{
      id: json[:id],
      created: json[:created] |> Check.datetime(),
      type: json[:type],
      ledger: json[:ledger] |> API.from_api_json(&Ledger.resource_maker/1)
    }
  end
end
