defmodule StarkInfra.IssuingRestock.Log do
  alias __MODULE__, as: Log
  alias StarkInfra.Utils.Rest
  alias StarkInfra.Utils.API
  alias StarkInfra.Utils.Check
  alias StarkInfra.IssuingRestock
  alias StarkInfra.User.Project
  alias StarkInfra.User.Organization
  alias StarkInfra.Error

  @moduledoc """
  Groups IssuingRestock.Log related functions
  """

  @doc """
  Every time an IssuingRestock entity is updated, a corresponding IssuingRestock.Log
  is generated for the entity. This log is never generated by the user, but
  it can be retrieved to check additional information on the IssuingRestock.

  ## Attributes (return-only):
    - `:id` [string]: unique id returned when the log is created. ex: "5656565656565656"
    - `:restock` [IssuingRestock]: IssuingRestock entity to which the log refers to.
    - `:type` [string]: type of the IssuingRestock event which triggered the log creation. ex: "created", "processing", "confirmed"
    - `:created` [DateTime]: creation datetime for the log.
  """
  @enforce_keys [
    :id,
    :restock,
    :type,
    :created
  ]
  defstruct [
    :id,
    :restock,
    :type,
    :created
  ]

  @type t() :: %__MODULE__{}

  @doc """
  Receive a single IssuingRestock.Log struct previously created by the Stark Infra API by its id

  ## Parameters (required):
    - `:id` [string]: struct unique id. ex: "5656565656565656"

  ## Options:
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - IssuingRestock.Log struct with updated attributes
  """
  @spec get(
    binary,
    user: Project.t() | Organization.t() | nil
  ) ::
    {:ok, Log.t()} |
    {:error, [Error.t()]}
  def get(id, options \\ []) do
    Rest.get_id(resource(), id, options)
  end

  @doc """
  Same as get(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec get!(
    binary,
    user: Project.t() | Organization.t() | nil
  ) :: Log.t()
  def get!(id, options \\ []) do
    Rest.get_id!(resource(), id, options)
  end

  @doc """
  Receive a stream of IssuingRestock.Log structs previously created in the Stark Infra API

  ## Options:
    - `:limit` [integer, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:after` [Date or string, default nil] date filter for structs created only after specified date. ex: ~D[2020-03-10]
    - `:before` [Date or string, default nil] date filter for structs created only before specified date. ex: ~D[2020-03-10]
    - `:types` [list of strings, default nil]: filter for log event types. ex: ["created", "processing", "confirmed"]
    - `:restock_ids` [list of strings, default nil]: list of IssuingRestock ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - stream of IssuingRestock.Log structs with updated attributes
  """
  @spec query(
    limit: integer,
    ids: [binary],
    after: Date.t() | binary,
    before: Date.t() | binary,
    types: [binary],
    restock_ids: [binary],
    user: Project.t() | Organization.t() | nil
  ) ::
    ({:cont, {:ok, [Log.t()]}} |
    {:error, [Error.t()]} |
    {:halt, any} |
    {:suspend, any},
    any -> any)
  def query(options \\ []) do
    Rest.get_list(resource(), options)
  end

  @doc """
  Same as query(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec query!(
    limit: integer,
    ids: [binary],
    after: Date.t() | binary,
    before: Date.t() | binary,
    types: [binary],
    restock_ids: [binary],
    user: Project.t() | Organization.t() | nil
  ) ::
    ({:cont, [Log.t()]} |
    {:error, [Error.t()]} |
    {:halt, any} |
    {:suspend, any},
    any -> any)
  def query!(options \\ []) do
    Rest.get_list!(resource(), options)
  end

  @doc """
  Receive a list of up to 100 IssuingRestock.Log structs previously created in the Stark Infra API and the cursor to the next page.
  Use this function instead of query if you want to manually page your requests.

  ## Options:
    - `:cursor` [string, default nil]: cursor returned on the previous page function call
    - `:limit` [integer, default 100]: maximum number of structs to be retrieved. It must be an integer between 1 and 100. ex: 50
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:after` [Date or string, default nil] date filter for structs created only after specified date. ex: ~D[2020-03-10]
    - `:before` [Date or string, default nil] date filter for structs created only before specified date. ex: ~D[2020-03-10]
    - `:types` [list of strings, default nil]: filter for log event types. ex: ["created", "processing", "confirmed"]
    - `:restock_ids` [list of strings, default nil]: list of IssuingRestock ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - list of IssuingRestock.Log structs with updated attributes
    - cursor to retrieve the next page of IssuingRestock.Log structs
  """
  @spec page(
    cursor: binary,
    limit: integer,
    ids: [binary],
    after: Date.t() | binary,
    before: Date.t() | binary,
    types: [binary],
    restock_ids: [binary],
    user: Project.t() | Organization.t() | nil
  ) ::
    {:ok, {binary, [Log.t()]}} |
    {:error, [Error.t()]}
  def page(options \\ []) do
    Rest.get_page(resource(), options)
  end

  @doc """
  Same as page(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec page!(
    cursor: binary,
    limit: integer,
    ids: [binary],
    after: Date.t() | binary,
    before: Date.t() | binary,
    types: [binary],
    restock_ids: [binary],
    user: Project.t() | Organization.t() | nil
  ) ::
    [Log.t()]
  def page!(options \\ []) do
    Rest.get_page!(resource(), options)
  end

  @doc false
  def resource() do
    {
      "IssuingRestockLog",
      &resource_maker/1
    }
  end

  @doc false
  def resource_maker(json) do
    %Log{
      id: json[:id],
      restock: json[:restock] |> API.from_api_json(&IssuingRestock.resource_maker/1),
      type: json[:type],
      created: json[:created] |> Check.datetime()
    }
  end
end
