defmodule StarkInfra.CreditNote.Log do
    alias __MODULE__, as: Log
    alias StarkInfra.Utils.Rest
    alias StarkInfra.Utils.API
    alias StarkInfra.Utils.Check
    alias StarkInfra.CreditNote
    alias StarkInfra.User.Project
    alias StarkInfra.User.Organization
    alias StarkInfra.Error

    @moduledoc """
    # CreditNote.Log object
        Every time an CreditNote entity is updated, a corresponding creditnote.Log
        is generated for the entity. This log is never generated by the user, but 
        it can be retrieved to check additional information on the CreditNote.
    ## Attributes:
        - `:id` [string]: unique id returned when the log is created. ex: "5656565656565656"
        - `:creditnote` [CreditNote]: CreditNote entity to which the log refers to.
        - `:errors` [list of strings]: list of errors linked to this CreditNote event
        - `:type` [string]: type of the CreditNote event which triggered the log creation. ex: "registered" or "paid"
        - `:created` [DateTime, default nil]: creation DateTime for the CreditNote. ex:  ~U[2020-3-10 10:30:0:0]
    """
    @enforce_keys [
        :id,
        :note,
        :errors,
        :type,
        :created
    ]
    defstruct [
        :id,
        :note,
        :errors,
        :type,
        :created
    ]

    @type t() :: %__MODULE__{}

    @doc """
    # Retrieve a specific CreditNote.Log
        Receive a single CreditNote.Log object previously created by the Stark Infra API by its id
    ## Parameters (required):
        - `:id` [string]: object unique id. ex: "5656565656565656"
    ## Parameters (optional):
        - `:user` [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.User was set before function call
    ## Return:
        - `:CreditNote.Log` object with updated attributes
    """
    @spec get(binary, user: Project.t() | Organization.t() | nil) ::
        { :ok, [Log.t()]} | {:error, [Error.t()]}
    def get(id, options \\ []) do 
        Rest.get_id(resource(), id, options)
    end 

    @doc """
    Same as get(), but it will unwrap the error tuple and raise in case of errors.
    """
    @spec get!(binary, user: Project.t() | Organization.t() | nil) :: Log.t()
    def get!(id, options \\ []) do 
        Rest.get_id!(resource(), id, options)
    end


    @doc """
    # Retrieve CreditNote.Logs
        Receive a generator of CreditNote.Log objects previously created in the Stark Bank API
    ## Parameters (optional):
        - `:limit` [integer, default nil]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
        - `:after` [Date or string, default nil] date filter for objects created only after specified date. ex: ~D[2020, 3, 10]
        - `:before` [Date or string, default nil] date filter for objects created only before specified date. ex: ~D[2020, 3, 10]
        - `:types` [list of strings, default []]: filter for log event types. ex: "paid" or "registered"
        - `:note_ids` [list of strings, default []]: list of CreditNote ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
        - `:user` [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.User was set before function call
    ## Return:
        - `:generator` of CreditNote.Log objects with updated attributes
    """
    @spec query(
        limit: integer,
        after: Date.t() | binary,
        before: Date.t() | binary,
        note_ids: [binary],
        user: Project.t() | Organization.t()
    ) :: 
    ({:cont, {:ok, [Log.t()]}}
     | {:error, [Error.t()]}
     | {:halt, any}
     | {:suspend, any},
      any -> 
        any)
    def query(options \\ []) do
        Rest.get_list(resource(), options)
    end

    @doc """
    Same as query(), but it will unwrap the error tuple and raise in case of errors.
    """
    @spec query!(
        limit: integer,
        after: Date.t() | binary,
        before: Date.t() | binary,
        note_ids: [binary],
        user: Project.t() | Organization.t()
    ) ::
    ( {:cont, [Log.t()]}
     | {:error, [Error.t()]}
     | {:halt, any}
     | {:suspend, any},
      any -> 
        any)
    def query!(options \\ []) do
        Rest.get_list!(resource(), options)
    end

    @doc """
    # Retrieve paged CreditNote.Logs
        Receive a list of up to 100 CreditNote.Log objects previously created in the Stark Bank API and the cursor to the next page.
        Use this function instead of query if you want to manually page your requests.
    ## Parameters (optional):
        - `:cursor` [string, default nil]: cursor returned on the previous page function call
        - `:limit` [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
        - `:after` [Date or string, default nil] date filter for objects created only after specified date. ex: ~D[2020, 3, 10]
        - `:before` [Date or string, default nil] date filter for objects created only before specified date. ex: ~D[2020, 3, 10]
        - `:types` [list of strings, default []]: filter for log event types. ex: "paid" or "registered"
        - `:note_ids` [list of strings, default []]: list of CreditNote ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
        - `:user` [Organization/Project object, default nil]: Organization or Project object. Not necessary if starkbank.user was set before function call
    ## Return:
        - `:list of CreditNote.Log objects with updated attributes
        - `:cursor to retrieve the next page of CreditNote.Log objects
    """
    @spec page(
        cursor: binary,
        limit: integer,
        after: Date.t() | binary,
        before: Date.t() | binary,
        note_ids: [binary],
        user: Project.t() | Organization.t()
    ) :: 
    {:ok, {binary, [Invoice.t()]}} | {:error, [Error.t()]}
    def page(options \\ []) do 
        Rest.get_page(resource(), options)
    end

    @doc """
    Same as page(), but it will unwrap the error tuple and raise in case of errors.
    """
    @spec page!(
        cursor: binary,
        limit: integer,
        after: Date.t() | binary,
        before: Date.t() | binary,
        note_ids: [binary],
        user: Project.t() | Organization.t()
    ) ::
       [Log.t()]
    def page!(options \\ []) do 
        Rest.get_page!(resource(), options)
    end

    @doc false
    def resource() do 
        {
            "CreditNoteLog",
            &resource_maker/1
        }
    end

    @doc false
    def resource_maker(json) do
        %Log{
            id: json[:id],
            note: json[:note] |> API.from_api_json(&CreditNote.resource_maker/1),
            created: json[:created] |> Check.datetime(),
            type: json[:type],
            errors: json[:errors]
        }
    end

end
