defmodule StarkInfra.PixClaim.Log do
    alias __MODULE__, as: Log
    alias StarkInfra.Utils.Rest
    alias StarkInfra.Utils.API
    alias StarkInfra.Utils.Check
    alias StarkInfra.PixClaim
    alias StarkInfra.User.Project
    alias StarkInfra.User.Organization
    alias StarkInfra.Error

    @moduledoc """
    Groups PixClaim.Log related functions
    """

    @doc """
    Every time a PixClaim entity is modified, a corresponding PixClaim.Log
    is generated for the entity. This log is never generated by the user.

    ## Attributes:
        - `:id` [string]: unique id returned when the log is created. ex: "5656565656565656"
        - `:created` [DateTime]: creation datetime for the log. ex: ~U[2020-3-10 10:30:0:0]
        - `:type` [string]: type of the PixClaim event which triggered the log creation. Options: “created”, “failed”, “delivering”, “delivered”, “confirming”, “confirmed”, “success”, “canceling” and “canceled”.
        - `:errors` [list of strings]: list of errors linked to this PixClaim event
        - `:agent` [string]: agent that modified the PixClaim resulting in the Log. Options: "claimer", "claimed".
        - `:reason` [string]: reason why the PixClaim was modified, resulting in the Log. Options: "fraud", "userRequested", "accountClosure", "defaultOperation", "reconciliation".
        - `:claim` [PixClaim]: PixClaim entity to which the log refers to.
    """
    @enforce_keys [
        :id,
        :created,
        :type,
        :errors,
        :agent,
        :reason,
        :claim
    ]
    defstruct [
        :id,
        :created,
        :type,
        :errors,
        :agent,
        :reason,
        :claim
    ]

    @type t() :: %__MODULE__{}

    @doc """
    Receive a single PixClaim.Log struct previously created by the Stark Infra API by its id

    ## Parameters (required):
        - `:id` [string]: struct unique id. ex: "5656565656565656"

    ## Options:
        - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

    ## Return:
        - PixClaim.Log struct with updated attributes
    """
    @spec get(
        id: binary,
        user: Project.t() | Organization.t() | nil
    ) ::
        { :ok, Log.t()} |
        {:error, [Error.t()]}
    def get(id, options \\ []) do
        Rest.get_id(resource(), id, options)
    end

    @doc """
    Same as get(), but it will unwrap the error tuple and raise in case of errors.
    """
    @spec get!(
        id: binary,
        user: Project.t() | Organization.t() | nil
    ) :: Log.t()
    def get!(id, options \\ []) do
        Rest.get_id!(resource(), id, options)
    end

    @doc """
    Receive a stream of PixClaim.Log structs previously created in the Stark Infra API

    ## Options:
        - `:ids` [list of strings, default nil]: Log ids to filter PixClaim Logs. ex: ["5656565656565656"]
        - `:limit` [integer, default 100]: maximum number of structs to be retrieved. Max = 100. ex: 35
        - `:after` [Date or string, default nil]: date filter for structs created after specified date. ex: ~D[2020, 3, 10]
        - `:before` [Date or string, default nil]: date filter for structs created before a specified date. ex: ~D[2020, 3, 10]
        - `:types` [list of strings, default nil]: filter retrieved structs by types. Options: “created”, “failed”, “delivering”, “delivered”, “confirming”, “confirmed”, “success”, “canceling” and “canceled”
        - `:claim_ids` [list of strings, default nil]: list of PixClaim ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
        - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

    ## Return:
        - stream of PixClaim.Log structs with updated attributes
    """
    @spec query(
        ids: [binary] | nil,
        limit: integer | nil,
        after: Date.t() | binary | nil,
        before: Date.t() | binary | nil,
        types: [binary] | nil,
        claim_ids: [binary] | nil,
        user: Project.t() | Organization.t() | nil
    ) ::
        {:ok, [Log.t()] } |
        {:error, [Error.t()]}
    def query(options \\ []) do
        Rest.get_list(resource(), options)
    end

    @doc """
    Same as query(), but it will unwrap the error tuple and raise in case of errors.
    """
    @spec query!(
        ids: [binary] | nil,
        limit: integer | nil,
        after: Date.t() | binary | nil,
        before: Date.t() | binary | nil,
        types: [binary] | nil,
        claim_ids: [binary] | nil,
        user: Project.t() | Organization.t() | nil
    ) :: [Log.t()]
    def query!(options \\ []) do
        Rest.get_list!(resource(), options)
    end

    @doc """
    Receive a list of up to 100 PixClaim.Log structs previously created in the Stark Infra API and the cursor to the next page.
    Use this function instead of query if you want to manually page your claims.

    ## Options:
        - `:cursor` [string, default nil]: cursor returned on the previous page function call
        - `:ids` [list of strings, default nil]: Log ids to filter PixClaim Logs. ex: ["5656565656565656"]
        - `:limit` [integer, default 100]: maximum number of structs to be retrieved. Max = 100. ex: 35
        - `:after` [Date or string, default nil]: date filter for structs created after a specified date. ex: ~D[2020, 3, 10]
        - `:before` [Date or string, default nil]: date filter for structs created before a specified date. ex: ~D[2020, 3, 10]
        - `:types` [list of strings, default nil]: filter retrieved structs by types. Options: “created”, “failed”, “delivering”, “delivered”, “confirming”, “confirmed”, “success”, “canceling” and “canceled”
        - `:claim_ids` [list of strings, default nil]: list of PixClaim IDs to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
        - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

    ## Return:
        - list of PixClaim.Log structs with updated attributes
        - cursor to retrieve the next page of PixClaim.Log structs
    """
    @spec page(
        cursor: binary | nil,
        ids: [binary] | nil,
        limit: integer | nil,
        after: Date.t() | binary | nil,
        before: Date.t() | binary | nil,
        types: [binary] | nil,
        claim_ids: [binary] | nil,
        user: Project.t() | Organization.t() | nil
    ) ::
        {:ok, {binary, [Log.t()]}} |
        {:error, [Error.t()]}
    def page(options \\ []) do
        Rest.get_page(resource(), options)
    end

    @doc """
    Same as page(), but it will unwrap the error tuple and raise in case of errors.
    """
    @spec page!(
        cursor: binary | nil,
        ids: [binary] | nil,
        limit: integer | nil,
        after: Date.t() | binary | nil,
        before: Date.t() | binary | nil,
        types: [binary] | nil,
        claim_ids: [binary] | nil,
        user: Project.t() | Organization.t() | nil
    ) ::
        {binary, [Log.t()]}
    def page!(options \\ []) do
        Rest.get_page!(resource(), options)
    end

    @doc false
    def resource() do
        {
            "PixClaimLog",
            &resource_maker/1
        }
    end

    @doc false
    def resource_maker(json) do
        %Log{
            id: json[:id],
            created:  json[:created] |> Check.datetime(),
            type: json[:type],
            errors: json[:errors],
            agent: json[:agent],
            reason: json[:reason],
            claim: json[:claim] |> API.from_api_json(&PixClaim.resource_maker/1)
        }
    end
end
