defmodule StarkInfra.IssuingEmbossingRequest.Log do
  alias __MODULE__, as: Log
  alias StarkInfra.Utils.Rest
  alias StarkInfra.Utils.API
  alias StarkInfra.Utils.Check
  alias StarkInfra.IssuingEmbossingRequest
  alias StarkInfra.User.Project
  alias StarkInfra.User.Organization
  alias StarkInfra.Error

  @moduledoc """
  Groups IssuingEmbossingRequest.Log related functions
  """

  @doc """
  Every time an IssuingEmbossingRequest entity is updated, a corresponding IssuingEmbossingRequest.Log
  is generated for the entity. This log is never generated by the user, but
  it can be retrieved to check additional information on the IssuingEmbossingRequest.

  ## Attributes (return-only):
    - `:id` [string]: unique id returned when the log is created. ex: "5656565656565656"
    - `:request` [IssuingEmbossingRequest]: IssuingEmbossingRequest entity to which the log refers to.
    - `:errors` [list of Error structs]: list of errors linked to this IssuingEmbossingRequest event. ex: [%StarkInfra.Error{code: "invalidDesign", message: "The design is not embossable"}]
    - `:type` [string]: type of the IssuingEmbossingRequest event which triggered the log creation. ex: "created", "sending", "sent", "processing", "success", "failed"
    - `:created` [DateTime]: creation datetime for the log.
  """
  @enforce_keys [
    :id,
    :request,
    :errors,
    :type,
    :created
  ]
  defstruct [
    :id,
    :request,
    :errors,
    :type,
    :created
  ]

  @type t() :: %__MODULE__{}

  @doc """
  Receive a single IssuingEmbossingRequest.Log struct previously created by the Stark Infra API by its id

  ## Parameters (required):
    - `:id` [string]: struct unique id. ex: "5656565656565656"

  ## Options:
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - IssuingEmbossingRequest.Log struct with updated attributes
  """
  @spec get(
    binary,
    user: Project.t() | Organization.t() | nil
  ) ::
    {:ok, Log.t()} |
    {:error, [Error.t()]}
  def get(id, options \\ []) do
    Rest.get_id(resource(), id, options)
  end

  @doc """
  Same as get(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec get!(
    binary,
    user: Project.t() | Organization.t() | nil
  ) :: Log.t()
  def get!(id, options \\ []) do
    Rest.get_id!(resource(), id, options)
  end

  @doc """
  Receive a stream of IssuingEmbossingRequest.Log structs previously created in the Stark Infra API

  ## Options:
    - `:limit` [integer, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:after` [Date or string, default nil] date filter for structs created only after specified date. ex: ~D[2020-03-10]
    - `:before` [Date or string, default nil] date filter for structs created only before specified date. ex: ~D[2020-03-10]
    - `:types` [list of strings, default nil]: filter for log event types. ex: ["created", "sending", "sent", "processing", "success", "failed"]
    - `:request_ids` [list of strings, default nil]: list of IssuingEmbossingRequest ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - stream of IssuingEmbossingRequest.Log structs with updated attributes
  """
  @spec query(
    limit: integer,
    ids: [binary],
    after: Date.t() | binary,
    before: Date.t() | binary,
    types: [binary],
    request_ids: [binary],
    user: Project.t() | Organization.t() | nil
  ) ::
    ({:cont, {:ok, [Log.t()]}} |
    {:error, [Error.t()]} |
    {:halt, any} |
    {:suspend, any},
    any -> any)
  def query(options \\ []) do
    Rest.get_list(resource(), options)
  end

  @doc """
  Same as query(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec query!(
    limit: integer,
    ids: [binary],
    after: Date.t() | binary,
    before: Date.t() | binary,
    types: [binary],
    request_ids: [binary],
    user: Project.t() | Organization.t() | nil
  ) ::
    ({:cont, [Log.t()]} |
    {:error, [Error.t()]} |
    {:halt, any} |
    {:suspend, any},
    any -> any)
  def query!(options \\ []) do
    Rest.get_list!(resource(), options)
  end

  @doc """
  Receive a list of up to 100 IssuingEmbossingRequest.Log structs previously created in the Stark Infra API and the cursor to the next page.
  Use this function instead of query if you want to manually page your requests.

  ## Options:
    - `:cursor` [string, default nil]: cursor returned on the previous page function call
    - `:limit` [integer, default 100]: maximum number of structs to be retrieved. It must be an integer between 1 and 100. ex: 50
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:after` [Date or string, default nil] date filter for structs created only after specified date. ex: ~D[2020-03-10]
    - `:before` [Date or string, default nil] date filter for structs created only before specified date. ex: ~D[2020-03-10]
    - `:types` [list of strings, default nil]: filter for log event types. ex: ["created", "sending", "sent", "processing", "success", "failed"]
    - `:request_ids` [list of strings, default nil]: list of IssuingEmbossingRequest ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkInfra.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - list of IssuingEmbossingRequest.Log structs with updated attributes
    - cursor to retrieve the next page of IssuingEmbossingRequest.Log structs
  """
  @spec page(
    cursor: binary,
    limit: integer,
    ids: [binary],
    after: Date.t() | binary,
    before: Date.t() | binary,
    types: [binary],
    request_ids: [binary],
    user: Project.t() | Organization.t() | nil
  ) ::
    {:ok, {binary, [Log.t()]}} |
    {:error, [Error.t()]}
  def page(options \\ []) do
    Rest.get_page(resource(), options)
  end

  @doc """
  Same as page(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec page!(
    cursor: binary,
    limit: integer,
    ids: [binary],
    after: Date.t() | binary,
    before: Date.t() | binary,
    types: [binary],
    request_ids: [binary],
    user: Project.t() | Organization.t() | nil
  ) ::
    [Log.t()]
  def page!(options \\ []) do
    Rest.get_page!(resource(), options)
  end

  @doc false
  def resource() do
    {
      "IssuingEmbossingRequestLog",
      &resource_maker/1
    }
  end

  @doc false
  def resource_maker(json) do
    %Log{
      id: json[:id],
      request: json[:request] |> API.from_api_json(&IssuingEmbossingRequest.resource_maker/1),
      errors: json[:errors] |> parse_errors(),
      type: json[:type],
      created: json[:created] |> Check.datetime()
    }
  end

  defp parse_errors(nil), do: []

  defp parse_errors(errors) do
    Enum.map(errors, fn
      %Error{} = error -> error
      error -> %Error{code: error["code"], message: error["message"]}
    end)
  end
end
